export const PartTypes = {
    BLADE: 'BLADE',
    RATCHET: 'RATCHET',
    BIT: 'BIT',
    LOCK_CHIP: 'LOCK_CHIP',
    MAIN_BLADE: 'MAIN_BLADE',
    ASSIST_BLADE: 'ASSIST_BLADE',
    OVER_BLADE: 'OVER_BLADE',
    METAL_BLADE: 'METAL_BLADE'
} as const;