services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
    depends_on:
      - db

  web:
    image: node:20
    working_dir: /app/web
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    depends_on:
      - web
      - api

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: beyblade_stats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: